[package]
name = "validation"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
redpanda-transform-sdk = "1.1.0"
serde = { version = "1.0.210", features = ["serde_derive"] }
serde_json = "1.0.128"
