[package]
name = "format"
version = "0.1.0"
edition = "2021"

[dependencies]
redpanda-transform-sdk = "1.1.0"
redpanda-transform-sdk-sr = "1.1.0"
serde = { version = "1.0.210", features = ["serde_derive"] }
serde_json = "1.0.128"
