input:
  kafka:
    addresses: ["redpanda-0:9092"]
    topics: ["unprocessed"]
    consumer_group: "ufrehgiurhiueh"
pipeline:
  processors:
  - schema_registry_decode:
      url: "http://redpanda-0:8081"
  - branch:
      processors:
        - ollama_chat:
            model: llama3.2:1b
            prompt: |
                    Your task is to extract senders and classify emails into one of the following categories:

                    Primary: Emails from people you know and messages that don’t appear in other tabs.
                    Social: Messages from social networks and media-sharing sites.
                    Promotions: Deals, offers, and other promotional emails.
                    Updates: Automated confirmations, notifications, statements, and reminders that may not need immediate attention.
                    Forums: Messages from online groups, discussion boards, and mailing lists.

                    Please output pure JSON using the following example:
                    {
                      "subject": "Welcome to our newsletter!",
                      "from_name": "John Doe",
                      "from_addr": "john.doe@example.com",
                      "body": "Thank you for subscribing to our newsletter. We'll keep you updated with the latest news and offers.",
                      "category": "Promotions"  // Could be: "Forums", "Primary", "Promotions", "Updates", or "Social"
                    }

                    Here is the email:
                    ${!this.content}
            response_format: json
      result_map: |
          root.output = this
output:
  kafka:
    addresses: ["redpanda-0:9092"]
    topic: "unverified"
