input:
  kafka:
    addresses: ["localhost:9092"]
    topics: ["unprocessed"]
    consumer_group: ""
pipeline:
  processors:
  - schema_registry_decode:
      url: "http://localhost:8081"
  - branch:
      processors:
        - ollama_chat:
            model: llama3.2:1b
            prompt: |
                    Your task is to extract senders and classify emails into one of the following categories:

                    Primary: Emails from people you know and messages that don’t appear in other tabs.
                    Social: Messages from social networks and media-sharing sites.
                    Promotions: Deals, offers, and other promotional emails.
                    Updates: Automated confirmations, notifications, statements, and reminders that may not need immediate attention.
                    Forums: Messages from online groups, discussion boards, and mailing lists.

                    Respond in JSON with the following schema:
                    {
                      "$schema": "http://json-schema.org/draft-07/schema#",
                      "type": "object",
                      "properties": {
                        "subject": {
                          "type": "string",
                          "description": "The subject line of the email"
                        },
                        "from_name": {
                          "type": "string",
                          "description": "The name of the sender"
                        },
                        "from_addr": {
                          "type": "string",
                          "format": "email",
                          "description": "The email address of the sender"
                        },
                        "body": {
                          "type": "string",
                          "description": "The main content of the email"
                        },
                        "category": {
                          "type": "string",
                          "enum": ["Forums", "Primary", "Promotions", "Updates", "Social"],
                          "description": "The category or type of the email"
                        }
                      },
                      "required": ["subject", "from_addr", "body"],
                      "additionalProperties": false
                    }


                    Here is the email:
                    ${!this.content.email}
            response_format: json
            result_map: |
                root = root.merge(this)
output:
  kafka:
    addresses: ["localhost:9092"]
    topic: "unverified"
