input:
  kafka:
    addresses: ["redpanda-0:9092"]
    topics: ["unprocessed"]
    consumer_group: "ufrehgiurhiueh"
pipeline:
  processors:
  - schema_registry_decode:
      url: "http://redpanda-0:8081"
  - branch:
      processors:
        - ollama_chat:
            model: llama3.2:3b
            prompt: |
                    Your task is to extract senders and classify emails into one of the following categories, and output it as JSON

                    Extract this information:
                    --
                    ${!this.content}
                    --

                    Answer in JSON using the following schema:
                    {
                      subject: string or null,
                      from_name: string or null,
                      from_addr: string,
                      body: string,
                      category: "Primary" or "Social" or "Promotions" or "Updates" or "Forums" or "Support"
                    }

                    For the category, use the following guide to help your decision

                    Primary: Emails from people you know and messages that don’t appear in other tabs.
                    Social: Messages from social networks and media-sharing sites.
                    Promotions: Deals, offers, and other promotional emails.
                    Updates: Automated confirmations, notifications, statements, and reminders that may not need immediate attention.
                    Forums: Messages from online groups, discussion boards, and mailing lists.
                    Support: Messages providing support to users of your business. These are frequently questions, or grievances
            response_format: json
      result_map: |
          root.output = this
output:
  kafka:
    addresses: ["redpanda-0:9092"]
    topic: "unverified"
logger:
  level: DEBUG
  format: logfmt
  add_timestamp: false
  static_fields:
    '@service': redpanda-connect
