input:
  kafka:
    addresses: ["redpanda-0:9092"]
    topics: ["unprocessed"]
    consumer_group: "ufrehgiurhiueh"
pipeline:
  processors:
  - schema_registry_decode:
      url: "http://redpanda-0:8081"
  - branch:
      processors:
        - ollama_chat:
            model: llama3.2:3b
            prompt: |
                    Your task is to extract senders and classify emails into one of the following categories, and output it as JSON:

                    Primary: Emails from people you know and messages that don’t appear in other tabs.
                    Social: Messages from social networks and media-sharing sites.
                    Promotions: Deals, offers, and other promotional emails.
                    Updates: Automated confirmations, notifications, statements, and reminders that may not need immediate attention.
                    Forums: Messages from online groups, discussion boards, and mailing lists.
                    Support: Messages providing support to users of your business. These are frequently questions, or grievances

                    For example an email formatted like this:
                    ```
                    Dan Goodman dan@danthegoodman.com\n\nMy hackathon submission\n\nDear redpanda team, i would like to submit this really neat project to the hackathon. I hope you like it!!!
                    ```

                    Would result in JSON like this:
                    {
                      "subject": "My hackathon submission", // optional
                      "from_name": "Dan Goodman", // optional
                      "from_addr": "dan@danthegoodman.com",
                      "body": "Dear redpanda team, i would like to submit this really neat project to the hackathon. I hope you like it!!!",
                      "category": "Primary"
                    }

                    If something is missing from the email, omit the JSON property rather than putting something blank in or hallucinating.

                    Here is the email:
                    ${!this.content}
            response_format: json
      result_map: |
          root.output = this
output:
  kafka:
    addresses: ["redpanda-0:9092"]
    topic: "unverified"
logger:
  level: DEBUG
  format: logfmt
  add_timestamp: false
  static_fields:
    '@service': redpanda-connect
